const val kotlin_version = "1.7.0"
const val coroutines_version = "1.6.4"
const val fragment_version = "1.3.6"
const val activity_version = "1.2.4"
const val lifecycle_version = "2.5.0"
const val splitties_version = "3.0.0"